#!/bin/sh
export __GL_DXVK_OPTIMIZATIONS=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_PATH="/home/jamie/wineprefixes/blizzard"
export WINEPREFIX="/home/jamie/wineprefixes/blizzard"
export WINEFSYNC=1 
export STAGING_SHARED_MEMORY=1 
export DXVK_ENABLE_NVAPI=1
export WINEDLLOVERRIDES="nvapi,nvapi64,dxgi=n"
export DXVK_STATE_CACHE_PATH="/home/jamie/wineprefixes/blizzard"
export VKD3D_CONFIG="dxr,dxr11"

wine="/opt/wine-tkg-wow-opt/bin/wine"
bnet="$WINEPREFIX/drive_c/Program Files (x86)/Battle.net/Battle.net.exe"
wow="$WINEPREFIX/drive_c/Program Files (x86)/World of Warcraft/_retail_/Wow.exe"

exec "$wine" "$wow"
